id: I9C689B62
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T08:35:02+00:00'
last_modified: '2022-06-07T14:55:57.191628+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ4827
  title: སྔགས་ཀྱི་ཡི་གེའི་ཀློག་ཚུལ་དངོས་བསྟན་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    45C2:
      image_group_id: I1KG9019
      title: ''
      total_pages: 28
      order: 1
      base_file: 45C2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
