id: P001751
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:19:05.474107
source_metadata:
  id: bdr:W4CZ4827
  title: སྔགས་ཀྱི་ཡི་གེའི་ཀློག་ཚུལ་དངོས་བསྟན་པ།
  author: ''
  volumes:
    61978b0eef6a4f968a0c2ddde4bb0e7c:
      image_group_id: I1KG9019
      title: ''
      volume_number: 1
      total_pages: 28
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
