id: P001751
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ4827
  title: སྔགས་ཀྱི་ཡི་གེའི་ཀློག་ཚུལ་དངོས་བསྟན་པ།
  author: ''
  volumes:
    61978b0eef6a4f968a0c2ddde4bb0e7c:
      image_group_id: I1KG9019
      title: ''
      volume_number: 1
      total_pages: 28
      base_file: v001.txt
